export type Category = 'All' | 'AI / CV' | 'Robotics' | 'Web Dev' | 'Data Science' | 'Academic';

export interface Project {
  id: string;
  title: string;
  description: string;
  longDesc: string;
  category: Category;
  tags: string[];
  github: string;
  demo?: string;
  featured?: boolean;
  size?: 'sm' | 'md' | 'lg';
  year: number;
  profile: 'personal' | 'university';
  commits?: number;
}

export const PROJECTS: Project[] = [
  {
    id: 'socialworld',
    title: 'SocialWorld 3D',
    description: 'Facebook users become buildings in a living 3D city — follower count = building height.',
    longDesc: 'A 3D city visualization where Facebook users become buildings. Built with React 18 + Three.js (WebGL), Node.js + Express backend, Supabase PostgreSQL, Facebook OAuth 2.0 + JWT. Features fly/drive modes, click buildings to view profiles, billboard ad placements.',
    category: 'Web Dev',
    tags: ['React', 'Three.js', 'WebGL', 'Node.js', 'Supabase', 'OAuth'],
    github: 'https://github.com/sandy001-kki/SocialWorld',
    featured: true,
    size: 'lg',
    year: 2026,
    profile: 'personal',
  },
  {
    id: 'agv-raspberry',
    title: 'AGV — Raspberry Pi',
    description: 'Autonomous Ground Vehicle with LiDAR mapping, line following & obstacle avoidance. Flutter app control.',
    longDesc: 'Fully functional Autonomous Ground Vehicle using Raspberry Pi 3 as central controller and Arduino Mega for sensor/motor control. Stack: Python WebSocket server, Arduino C++ firmware, Flutter mobile app. Hardware: YDLIDAR X2, IR array, MPU6050 gyroscope. Modes: Manual joystick, line following, obstacle avoidance.',
    category: 'Robotics',
    tags: ['Python', 'Flutter', 'C++', 'Raspberry Pi', 'Arduino', 'LiDAR'],
    github: 'https://github.com/sandy001-kki/agv-raspberry-pi-mega',
    featured: true,
    size: 'lg',
    year: 2026,
    profile: 'personal',
  },
  {
    id: 'agv-esp32',
    title: 'AGV — ESP32',
    description: 'AGV prototype with Windows laptop + ESP32, live 360° LiDAR mapping over WiFi.',
    longDesc: 'AGV variant using a Windows laptop + ESP32 microcontroller. Python WebSocket server (port 8765), HTTP web interface (port 8080), Flutter app, ESP32 firmware. Live 360° LiDAR mapping, multi-interface control (mobile/web/joystick), autonomous obstacle avoidance over WiFi.',
    category: 'Robotics',
    tags: ['Python', 'Flutter', 'ESP32', 'LiDAR', 'WebSocket', 'C++'],
    github: 'https://github.com/sandy001-kki/agv-laptop-esp32',
    featured: true,
    size: 'md',
    year: 2026,
    profile: 'personal',
  },
  {
    id: 'weapon-detection',
    title: 'Weapon Detection AI',
    description: 'Real-time YOLOv8 weapon detection from surveillance cameras with multi-channel alerts.',
    longDesc: 'AI-powered security system detecting weapons in surveillance footage using YOLOv8 nano. SQLite database, multi-channel alerts: email, SMS, Telegram, local alarm. Modules: detector, dashboard, emailer, sms_alert, telegram_alert, alarm, scheduler, snapshot.',
    category: 'AI / CV',
    tags: ['Python', 'YOLOv8', 'OpenCV', 'SQLite', 'Telegram API'],
    github: 'https://github.com/sandy001-kki/Security-Cams-Weapon-Detection-',
    featured: true,
    size: 'md',
    year: 2026,
    profile: 'personal',
  },
  {
    id: 'air-writing',
    title: 'Air Writing System',
    description: 'Touchless hand-gesture writing using MediaPipe — draw, erase, OCR, and save with your finger.',
    longDesc: 'AI-based hand gesture recognition enabling touchless writing, color selection, erasing, saving drawings, and modular OCR using computer vision. Stack: OpenCV, MediaPipe. Index finger = draw, index+middle = pause, fist = erase, hover over toolbar = select tools. Demo video on YouTube.',
    category: 'AI / CV',
    tags: ['Python', 'OpenCV', 'MediaPipe', 'OCR', 'Computer Vision'],
    github: 'https://github.com/sandy001-kki/Air-Writing-System',
    featured: true,
    size: 'md',
    year: 2026,
    profile: 'personal',
  },
  {
    id: 's5-attendance',
    title: 'AI Attendance System',
    description: 'Facial recognition attendance system for university — 160 commits, production-grade with Firebase.',
    longDesc: 'AI-powered Attendance Management System built for university environments using Next.js, Firebase Auth, and Cloud Firestore. TensorFlow.js + face-api.js for facial recognition. Role-based dashboards (faculty & admin), digital signature verification, automated Excel export.',
    category: 'AI / CV',
    tags: ['Next.js', 'TypeScript', 'TensorFlow.js', 'face-api.js', 'Firebase'],
    github: 'https://github.com/11249a040-sandeep/S5-attendence',
    featured: true,
    size: 'lg',
    year: 2026,
    profile: 'university',
    commits: 160,
  },
  {
    id: 'image-editor',
    title: 'Image Editor',
    description: 'Desktop image editor with PyQt5/OpenCV — brightness, crop, compare, export as .exe.',
    longDesc: 'Desktop image editing application. Stack: PyQt5 (GUI), OpenCV, NumPy, PyInstaller for distribution. Features: multi-image loading, brightness/contrast/exposure sliders, before/after comparison, crop, zoom, action logging to logs.txt. Buildable as standalone .exe with Inno Setup installer.',
    category: 'AI / CV',
    tags: ['Python', 'PyQt5', 'OpenCV', 'NumPy', 'PyInstaller'],
    github: 'https://github.com/sandy001-kki/image_editor_python',
    size: 'sm',
    year: 2026,
    profile: 'personal',
  },
  {
    id: 'fitness-pro',
    title: 'Sandy Fitness Pro',
    description: 'PWA merging academic timetable + fitness tracking with OLED UI — no frameworks, pure JS.',
    longDesc: 'Progressive Web App combining academic timetable management and fitness tracking with OLED-optimized UI. Live timetable auto-detects current day, strength training tracker, 1RM personal bests, rest timer, water intake logger, streak tracking, JSON export. Installable on Android/iOS.',
    category: 'Web Dev',
    tags: ['JavaScript', 'PWA', 'HTML5', 'CSS3', 'Local Storage'],
    github: 'https://github.com/sandy001-kki/sandy-fitness-pro',
    size: 'md',
    year: 2026,
    profile: 'personal',
  },
  {
    id: 'portfolio-site',
    title: 'Portfolio v1',
    description: 'Previous personal portfolio built with Next.js + Firebase Studio — 66 commits.',
    longDesc: 'Personal portfolio website built with Next.js + Firebase Studio. Stack: Next.js, TypeScript, Tailwind CSS, Firebase/Firestore, PostCSS.',
    category: 'Web Dev',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'Firebase'],
    github: 'https://github.com/sandy001-kki/portfolio',
    size: 'sm',
    year: 2026,
    profile: 'personal',
    commits: 66,
  },
  {
    id: 'scsvmv-outly',
    title: 'SCSVMV Outreach',
    description: 'University outreach management tool built with Next.js + Firebase — 42 commits.',
    longDesc: 'Next.js app built in Firebase Studio — outreach/management tool for SCSVMV university. Stack: Next.js, TypeScript, Tailwind CSS, Firebase App Hosting.',
    category: 'Web Dev',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'Firebase'],
    github: 'https://github.com/sandy001-kki/scsvmv-outly',
    size: 'sm',
    year: 2026,
    profile: 'personal',
    commits: 42,
  },
  {
    id: 'sales-ml-dashboard',
    title: 'Sales ML Dashboard',
    description: 'Interactive R Shiny dashboard — Random Forest model predicts export sales from meat inputs.',
    longDesc: 'Interactive ML dashboard built with R and Shiny that predicts total export sales from beef, pork, and poultry inputs using Random Forest regression. Real-time prediction sliders, bulk CSV upload, model info panel, data visualization. Use cases: sales forecasting, export planning, supply chain optimization.',
    category: 'Data Science',
    tags: ['R', 'Shiny', 'Random Forest', 'Machine Learning', 'bslib'],
    github: 'https://github.com/11249a040-sandeep/sales-prediction-ml-dashboard-r',
    featured: true,
    size: 'md',
    year: 2026,
    profile: 'university',
  },
  {
    id: 'sales-forecast',
    title: 'ARIMA Sales Forecaster',
    description: 'Time series 12-month sales forecasting using ARIMA model and ggplot2 visualization in R.',
    longDesc: 'Time series forecasting project using ARIMA modeling on monthly sales data. Stack: R, forecast package, ggplot2. Output: 12-month sales forecast.',
    category: 'Data Science',
    tags: ['R', 'ARIMA', 'ggplot2', 'Time Series', 'Forecasting'],
    github: 'https://github.com/11249a040-sandeep/sales-forecast-r',
    size: 'sm',
    year: 2026,
    profile: 'university',
  },
  {
    id: 'todo-app',
    title: 'Task Manager App',
    description: 'Responsive to-do app with priority levels, due dates, search/filter, and Local Storage auth.',
    longDesc: 'Simple and responsive To-Do List web application. Stack: Vanilla HTML/CSS/JS, Local Storage. Features: user authentication, add/edit/delete/complete tasks, due dates, priority levels (High/Medium/Low with color coding), search/filter, data persistence.',
    category: 'Web Dev',
    tags: ['JavaScript', 'HTML', 'CSS', 'Local Storage'],
    github: 'https://github.com/11249a040-sandeep/todo-list-app',
    size: 'sm',
    year: 2026,
    profile: 'university',
  },
  {
    id: 'netflix-clone',
    title: 'Netflix Clone',
    description: 'Front-end Netflix UI recreation in plain HTML/CSS/JavaScript.',
    longDesc: 'Netflix clone front-end project — recreation of Netflix\'s UI in plain HTML/CSS/JS. Contained in the Projects repository on university account.',
    category: 'Web Dev',
    tags: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/11249a040-sandeep/Projects',
    size: 'sm',
    year: 2026,
    profile: 'university',
  },
  {
    id: 'face-detection',
    title: 'Face Detection',
    description: 'Haar cascade face detection using OpenCV — grayscale conversion, bounding boxes, output PNG.',
    longDesc: 'Face detection using Haar cascades (OpenCV). Stack: Python 3.12, OpenCV (headless), NumPy, pre-trained Haarcascade classifier. Converts image to grayscale, runs detectMultiScale(), draws bounding boxes, saves out.png.',
    category: 'AI / CV',
    tags: ['Python', 'OpenCV', 'Haar Cascade', 'NumPy'],
    github: 'https://github.com/11249a040-sandeep/face-detection-haarcascade',
    size: 'sm',
    year: 2026,
    profile: 'university',
  },
  {
    id: 'scsvmv-labs',
    title: 'University Labs',
    description: 'Multi-semester academic coursework: DAA, DSA, OOP, Python — C++/C/Python/Jupyter.',
    longDesc: 'Multi-semester academic coursework collection. Includes: DAA_LAB_SEM_4 (Design and Analysis of Algorithms), DSA_LAB_SEM3, OOPS_LAB_3, PYTHON_LAB_SEM_3, and Jupyter notebooks.',
    category: 'Academic',
    tags: ['C++', 'Python', 'C', 'Jupyter', 'Algorithms', 'DSA'],
    github: 'https://github.com/11249a040-sandeep/SCSVMV_LABS',
    size: 'sm',
    year: 2026,
    profile: 'university',
    commits: 18,
  },
  {
    id: 'oops-lab',
    title: 'OOP Lab — C++',
    description: '39 C++ programs: classes, inheritance, operator overloading, templates, exception handling.',
    longDesc: '39 C++ programs from OOP Laboratory at SCSVMV University. Covers: classes (StudentRecord, BankAccount, LaptopDetails), inheritance (Basic, Multilevel), operator overloading, virtual/abstract classes, templates, exception handling, practical systems (StudentManagementSystem, LibraryManagement, EmployeePayroll), dynamic memory allocation.',
    category: 'Academic',
    tags: ['C++', 'OOP', 'Templates', 'Inheritance', 'Exception Handling'],
    github: 'https://github.com/11249a040-sandeep/OOPS-LAB',
    size: 'sm',
    year: 2025,
    profile: 'university',
    commits: 39,
  },
  {
    id: 'robotic-car',
    title: 'Arduino Robotic Car',
    description: 'Entry-level Arduino robotic car — the starting point before the AGV projects.',
    longDesc: 'Arduino-based robotic car project. Documentation in a Word doc. Beginner hardware project predating the more sophisticated AGV repos.',
    category: 'Robotics',
    tags: ['Arduino', 'C++', 'Hardware'],
    github: 'https://github.com/sandy001-kki/Roboyic-car',
    size: 'sm',
    year: 2025,
    profile: 'personal',
  },
  {
    id: 'ascii-games',
    title: 'ASCII Space Invaders',
    description: 'Text-based ASCII Space Invaders in the terminal — pure Python, progressive difficulty.',
    longDesc: 'Text-based ASCII Space Invaders clone running in the terminal. Controls: a/d to move ship, s to fire. Progressive difficulty scaling, no external dependencies (pure Python 3.x).',
    category: 'Academic',
    tags: ['Python', 'Game', 'Terminal', 'ASCII'],
    github: 'https://github.com/11249a040-sandeep/games-',
    size: 'sm',
    year: 2026,
    profile: 'university',
  },
  {
    id: 'leetcodes',
    title: 'LeetCode Solutions',
    description: 'Personal LeetCode solutions in Python — Two Sum and growing.',
    longDesc: 'Personal LeetCode solutions repository in Python.',
    category: 'Academic',
    tags: ['Python', 'Algorithms', 'LeetCode', 'DSA'],
    github: 'https://github.com/sandy001-kki/leetcodes',
    size: 'sm',
    year: 2026,
    profile: 'personal',
  },
];

export const CATEGORIES: Category[] = ['All', 'AI / CV', 'Robotics', 'Web Dev', 'Data Science', 'Academic'];

export const FEATURED = PROJECTS.filter(p => p.featured);
